apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: client-image
        image: client
        ports:
        - containerPort: 80